#!/usr/bin/env bash

function main {
  set -exfu

  cd "${PLUGIN_SOURCE:-.}"

  pkg --out-path "${PLUGIN_OUTPUT_DIR:-.}" -t "${PLUGIN_TARGET:-node12-macos-x64,node12-linux}" "${PLUGIN_SCRIPT}"

  return 0
}

main "$@"
