#!/usr/bin/env bash

function main {
  set -exfu

  ls -ltrhd /drone/src /drone/src/.defn || true

  : ${PLUGIN_SOURCE:=.}
  : ${PLUGIN_OUTPUT_DIR:=.}
  : ${PLUGIN_TARGET:=node12-macos-x64,node12-linux}

  cd "${PLUGIN_SOURCE}"

  if [[ ! -w "${PLUGIN_OUTPUT_DIR}" ]]; then
    PLUGIN_OUTPUT_DIR="/tmp"
  fi

  pkg --out-path "${PLUGIN_OUTPUT_DIR}" -t "${PLUGIN_TARGET}" "${PLUGIN_SCRIPT}"

  return 0
}

main "$@"
